#===========================================================
# SITE SETTINGS
#===========================================================

locale: "ar"
title: "حبر شفاف"
description: "مساحة للكتابة الصادقة، الأفكار الواضحة، والتأملات التي تعبر عن الذات." # تم تغيير الوصف هنا
url: "https://djameldidin.github.io"
baseurl: "/hibr-shafaf" 
repository: "djameldidin/hibr-shafaf" 

#===========================================================
# THEME SETTINGS
#===========================================================

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

#===========================================================
# AUTHOR SETTINGS
#===========================================================

author:
  name: "عدلي رغدة"
  avatar: "/assets/images/profile.jpg"
  bio: "أؤمن أن أبسط فكرة يمكنها أن تغيّر نظرتنا للعالم إذا قُدمت في قالب جميل. هنا مساحة للكتابة والتأملات."
  location: "الجزائر"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/djameldidin"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:raghdachaimaa@gmail.com"

#===========================================================
# COLLECTIONS
#===========================================================

collections:
  articles:
    output: true
    permalink: /articles/:path/
  thoughts:
    output: true
    permalink: /thoughts/:path/
  life_stories:
    output: true
    permalink: /life-stories/:path/

#===========================================================
# PLUGINS & DEFAULTS
#===========================================================

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"
future: true

#===========================================================
# COMMENTS SETTINGS (disqus)
#===========================================================
comments:
  provider: "disqus"
  disqus:
    shortname: "https-djameldidin-github-io-hibr-shafaf"

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
      comments: true

  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: single
      author_profile: true
      share: true
      read_time: false
      comments: true

  - scope:
      path: ""
      type: "life_stories"
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
      comments: true

  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      comments: true

version: "{{ site.time | date: '%s' }}"
# في أي مكان من ملف _config.yml
include:
  - _includes/head-custom.html


  
